name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Prevent duplicate builds
concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo docker system prune -af
          df -h
          
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: remphan
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      - name: Build Docker Image
        run: docker build --no-cache -t remphan/visomasterdockah:latest -f Dockerfile-icewm .

      - name: Push Docker Image
        run: docker push remphan/visomasterdockah:latest
